#!/bin/bash

set -e

#CEF_BUILD_DIR=../cef-build
CEF_BUILD_DIR=/media/patriot0/dev/cef-build-1
BINARY_DIR=./code/chromium_git/chromium/src/cef/binary_distrib
DOWNLOAD_DIR=cefsdk/download

die() {
    echo "ERR: $*" >&2
    exit 1
}

(cd $CEF_BUILD_DIR) || die "failed to chdir into $CEF_BUILD_DIR"

FN=`echo $CEF_BUILD_DIR/$BINARY_DIR/cef_binary_*_linux64.tar.bz2`
BN=`basename "$FN"`

echo "Using CEF tarball: $FN"

[ -f "$FN" ] || die "cant find tarball file: $FN"

mkdir -p $DOWNLOAD_DIR

cp $FN $DOWNLOAD_DIR || die "failed copying $FN to $DOWNLOAD_DIR"
( cd $DOWNLOAD_DIR && ln -sf $BN cef.tar.bz2 )
